hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://eureka_user:eu1234fHAgg@registry:8761/eureka/
      defaultZone: http://eureka_user:eu1234fHAgg@localhost:8761/eureka/

security:
  oauth2:
    resource:
#      user-info-uri: http://gateway:4001/uaa/users/current
      user-info-uri: http://localhost:4001/uaa/users/current
