server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka_user:eu1234fHAgg@localhost:8761/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
